- id: doi:10.1016/B978-0-443-15754-7.00049-3
  type: book
  image: assets/papers/images/PohAdcock_Book_2024.jpg
  buttons:
    - type: pdf
      link: assets/papers/pdf/PohAdcock_Book_2024.pdf

- id: doi:10.1073/pnas.2301974120   
  type: paper
  image: assets/papers/images/HsiungEtAl_PNAS_2023.jpg
  buttons:
    - type: pdf
      link: assets/papers/pdf/HsiungEtAl_PNAS_2024.pdf

- id: doi:10.1038/s41467-022-34459-3
  type: paper
  image: assets/papers/images/PohEtAl_NatComms_2022.jpg
  buttons:
    - type: pdf
      link: assets/papers/pdf/PohEtAl_NatComms_2022.pdf
